server:
  port: 90
logging:
  level:
    root: INFO
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      dll-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: